 okay so now analyze the src folder and as we use several prompts files to inject and compound the ai agent system message (which uses gemini 2.5) write one new, or update the prompt text file for clarifying these things: 1- Rice servings must   │
 │   have a minimum of 2 people servings and it cannot accept two rices types for the same booking. 2- It can accept less rice servings than the partySize of booking, for example 2 servings of rice for a booking of 5 people, because the other 3      │
 │   people is deduced will choose something else from the menu in the restaurant. 3- It must ask if they do need 'Tronas' highChairs and if they bring 'Carritos de bebe' babyStrolls as the full booking insertion needs the information as you can     │
 │   check in the booking insertion program. 4- If the client message includes a rice type it must be verified with the rice verify path that fetches rice types from the database and calls a new ai agent to compare and verifyt the rice type inputed  │
 │   by the user and the ones fetched from database to just return a simple true false response so that the agent can send a response with human behaviour following the booking or telling we do not have that rice in the menu and sending a send/menu  │
 │   uazapi with the link to menufindesemana. 5- If the client has not told anything about a rice yet, the ai agent must ask about if they do want to book a rice as they must be booked, if the answer is no arrozType and arrozServings are set to null │
 │    and we can continue, if it says yes we must verify which arrozType and how many arrozServings of that rice. 6- The booking information we must collect is: name (uazapi webhook information from whatsapp's name), phone (uazapi webhook            │
 │   information from whatsapp sender phone number), partySize, reservation_time, date, arrozType (one from the database verified or null), arrozServings (minimun 2 or null), highChairs (0 or number with maximum 3 per booking), babyStrollers (0 or   │
 │   number maximum 3 per booking). 7- When the user tells the date we must run a verification first with the database that does what exactly what this backend php does but with c sharp: first                                                          │
 │   /home/jaime/Documents/projects/botGenerator/php/check_day_status.php, and if the day is closed send uazapi message, if the day is open the program will continue with what this does:     /home/jaime/Documents/projects/botGenerator/php/fetch_daily_limit.php and check how manu positive free booking seats are compared to the partySize the client sent and if there is not enough free bookin seats send uazapi whatsapp to inform so and create a new database query to check the next most proxime day where there is enough free bookin seats and that is open to guide the user and offer another day to book, but if for that given day there are enough free booking days the program will continue what this code does: /home/jaime/Documents/projects/botGenerator/php/gethourdata.php and if the client's time data is not factible send uazapi whatsapp informing so and proposing other available hours, if none of available hours fit the party size the client told use the previous created program code to find the next proximate date where there are free booking seats for that party size in an hour time or various hour times, but if there is enough room for the hour time the client intially said just continue, gather the information and continue asking for the needed booking information if we still do not have all gethered. 
 With all these information, analyze the code, the prompts, and make the updates/creations needed to make the entire flow work as I have commanded. You can check the database schema by checking mysql with user: root and password: 123123. For any sudo operations on linux use echo password: 123123